# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Papers
    url: 'papers/'
    weight: 20
  - name: Books
    url: 'books/'
    weight: 30
  - name: Macro with Python
    url: 'https://macro-with-python.netlify.app/'
    weight: 40
  - name: El Hub Económico
    url: 'https://www.elhubeconomico.com/'
    weight: 50
  - name: Blog
    url: 'https://puntodevistaeconomico.com/'
    weight: 60
  - name: FMI Graduate Seminar
    url: 'FMI/'
    weight: 70

# Link to a PDF of your resume/CV from the menu.
# To enable, copy your resume/CV to `static/uploads/resume.pdf` and uncomment the lines below.
#  - name: CV
#    url: uploads/resume.pdf
#    weight: 70
