# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: '#about'
    weight: 10
  - name: Papers
    url: 'papers/'
    weight: 20
  - name: Books
    url: 'books/'
    weight: 30
  - name: Macro with Python
    url: 'https://macro-with-python.netlify.app/'
    weight: 40
  - name: El Hub Económico
    url: 'https://www.elhubeconomico.com/'
    weight: 50
  - name: Media
    url: 'media/'
    weight: 60
  - name: Blog
    url: 'https://puntodevistaeconomico.com/'
    weight: 70
  - name: FMI Graduate Seminar
    url: 'fmi/'
    weight: 80